name: Selenium Tests - Daily Run and Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 9 * * *' # At 09:00 UTC every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    - name: Build with Maven (skip tests)
      run: mvn clean install -DskipTests

    - name: Run TestNG tests
      run: mvn test -Dsurefire.suiteXmlFiles=testng.xml

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: target/surefire-reports

    - name: Send email notification
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: TestNG Daily Run Report - ${{ job.status }}
        body: |
          Hello,

          The daily TestNG test run has completed.
          Status: ${{ job.status }}

          You can view the workflow run details here:
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          Best regards,
          Your CI/CD System
        to: ananthtesting96@gmail.com
        from: GitHub Actions <abhiramik.bca@gmail.com>
      env:
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
